"""init

Revision ID: 8cc83f9fdc82
Revises: 
Create Date: 2025-10-07 23:21:00.829905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cc83f9fdc82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('buttons', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sending',
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('reminder_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['reminder_to_id'], ['sending.distributor_id'], ),
    sa.PrimaryKeyConstraint('distributor_id')
    )
    op.create_table('feedbacks',
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('sending_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sending_id'], ['sending.distributor_id'], ),
    sa.PrimaryKeyConstraint('distributor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    op.drop_table('sending')
    op.drop_table('messages')
    # ### end Alembic commands ###
